Update build-release.yml

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -46,6 +46,21 @@ jobs:
           echo "${{ env.OSBOX_BOARD }}"
           #echo "::set-env name=OSBOX_BOARD::$OSBOX_BOARD"          
         id: extract_board
+      - name: Testje
+        shell: bash
+        run: |
+          _ORG_NAME="jerryhopper"
+          _REPO_NAME="sw-osbox-bin"
+          _LATEST_VERSION=$(curl -s https://api.github.com/repos/${_ORG_NAME}/${_REPO_NAME}/releases/latest|jq .tag_name -r )
+          echo "https://api.github.com/repos/${_ORG_NAME}/${_REPO_NAME}/releases/latest"
+          echo $_LATEST_VERSION
+          echo "https://github.com/${_ORG_NAME}/${_REPO_NAME}/archive/${_LATEST_VERSION}.tar.gz"
+          DOWNLOAD_CODE=$(curl -L -s -o /dev/null -I -w "%{http_code}" https://github.com/${_ORG_NAME}/${_REPO_NAME}/archive/${_LATEST_VERSION}.tar.gz)
+          if [ "$DOWNLOAD_CODE" != "200" ];then
+            echo "Download error! ( ${DOWNLOAD_CODE} ) "https://github.com/${_ORG_NAME}/${_REPO_NAME}/archive/${_LATEST_VERSION}.tar.gz""
+              exit 1
+          fi
+          echo "OSBOX_ARCHIVE=https://github.com/${_ORG_NAME}/${_REPO_NAME}/archive/${_LATEST_VERSION}.tar.gz" >> $GITHUB_ENV
       # Runs a set of commands using the runners shell
       - name: Get Armbian build enviroment
         run: |
